cq.git/cityquest/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, url
from cityquest import views

urlpatterns = patterns('',
    url(r'^home/', views.home),
    url(r'^event/(?P<event_id>\d+)/(?P<slug>[-\w]+)/', views.event),
    url(r'^eventlist/', views.eventlist),
    url(r'^create/', views.createevent),
    url(r'^edit/(?P<event_id>\d+)/(?P<slug>[-\w]+)/', views.editevent),
    url(r'^attend/(?P<event_id>\d+)/', views.attend),
    url(r'^unattend/(?P<event_id>\d+)/', views.unattend),
    url(r'^comment/(?P<event_id>\d+)/', views.commentevent),
    url(r'^myprofile/', views.myprofile),
    url(r'^editprofile/', views.editprofile),
)

cq.git/cq/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cityquest/', include('cityquest.urls')),
    url(r'^login/', "django.contrib.auth.views.login", {'template_name': 'login.html'}),
    url(r'^logout/$', 'cq.views.logout'),
    url(r'^register/$', 'cq.views.register_user'),
    url(r'^register_success/$', 'cq.views.register_success'),
)

urlpatterns += staticfiles_urlpatterns()

cq.git/cityquest/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.contrib.auth.models import AbstractUser
from time import time
from math import radians, cos, sin, asin, sqrt

class Event(models.Model):
    eventname = models.CharField(max_length = 100, null = False)
    address = models.CharField(max_length = 200, null = False)
    CATEGORIES = (
        (u'Business', u'Business'),
        (u'Charity', u'Charity'),
        (u'ClassesWorkshops', u'Classes & Workshops'),
        (u'Conferences', u'Conferences'),
        (u'Festivals', u'Festivals'),
        (u'FoodDrinks', u'Food & Drinks'),
        (u'MusicConcerts', u'Music & Concerts'),
        (u'Networking', u'Networking'),
        (u'Nightlife', u'Nightlife'),
        (u'PerformingArts', u'Performing Arts'),
        (u'ScienceTech', u'Science & Tech'),
        (u'Spirituality', u'Spirituality'),
        (u'Sports', u'Sports'),
        (u'Other', u'Other')
    )
    category = models.CharField(max_length = 30, choices = CATEGORIES, null = False)
    price = models.DecimalField(null = False, max_digits = 7, decimal_places = 2)
    datetime = models.DateTimeField(null = False)
    description = models.TextField(null = True, blank = True)
    public = models.BooleanField()
    owner = models.ForeignKey('UserProfile', blank = True, null = True)
    attendees = models.IntegerField(blank = True, null = True, default = 1)
    slug = models.SlugField(blank = True, null = True)
    longitude = models.FloatField(blank = True, null = True)
    latitude = models.FloatField(blank = True, null = True)

    def __str__(self):
        return self.eventname

    def haversine(self, lon, lat):
        """
        Calculate the great circle distance between two points 
        on the earth (specified in decimal degrees)
        """
	# convert lon and lat to floats first
	lon = float(lon)
	lat = float(lat)
        # convert decimal degrees to radians 
        lon1, lat1, lon2, lat2 = map(radians, [lon, lat, self.longitude, self.latitude])

        # haversine formula 
        dlon = lon2 - lon1 
        dlat = lat2 - lat1 
        a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
        c = 2 * asin(sqrt(a)) 

        # 6367 km is the radius of the Earth
        km = 6367 * c
        return km

class Attendee(models.Model):
    username = models.ForeignKey('UserProfile')
    eventname = models.ForeignKey('Event')

class Comment(models.Model):
    username = models.ForeignKey('UserProfile')
    eventname = models.ForeignKey('Event')
    commentbody = models.TextField(null = True, blank = True)

    def __str__(self):
        return self.commentbody


class UserProfile(AbstractUser):
    about_me = models.TextField(null = True, blank = True)
    ph_number = models.CharField(max_length = 15, null = True, blank = True)
    age = models.IntegerField(null = True, blank = True)
    SEX_CHOICES = (
        (u'1', u'Female'),
        (u'2', u'Male'),
    )
    sex = models.CharField(max_length = 1, choices = SEX_CHOICES)
    location = models.CharField(max_length = 100, null = True, blank = True)

    def __str__(self):
        return self.ph_number

cq.git/cityquest/forms.py
from django import forms
from cityquest.models import Event, UserProfile, Comment
from django.forms import ModelForm
from cityquest.admin import newUserChangeForm
from django.contrib.auth import get_user_model

class EventForm(ModelForm):
    class Meta:
        model = Event

class UserForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('about_me','ph_number', 'age', 'sex', 'location')

class EditEventForm(ModelForm):
    class Meta:
        model = Event
        fields = ('eventname', 'address', 'category', 'datetime', 'price', 'description', 'public', 'latitude', 'longitude')

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('commentbody',)

cq.git/cityquest/views.py
from django.shortcuts import render_to_response, render, get_object_or_404 
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from cityquest.models import Event, UserProfile, Attendee, Comment
from cityquest.forms import EventForm, UserForm, EditEventForm, CommentForm
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
from cityquest.admin import newUserChangeForm
from django.contrib.auth.forms import UserChangeForm


def event(request, event_id, slug):
#    event_cache_key = 'event_page' + str(event_id)
#    cache_time = 360 #TTL
#    result = cache.get(event_cache_key)
    event = Event.objects.get(id = event_id)
    attendees = Attendee.objects.filter(eventname = event)
    owner = get_user_model().objects.get(username = event.owner.username)
    comments = Comment.objects.filter(eventname = event)
    if request.user.is_authenticated():
        isAttending = Attendee.objects.filter(username = request.user).filter(eventname = event)
    else: 
        isAttending = 'none'
#    if not result:
    result = render_to_response('cityquest/event.html', {"event": event, "owner": owner, "attendees": attendees, "comments": comments, "isAttending": isAttending}, context_instance=RequestContext(request))
#        cache.set(event_cache_key, result, cache_time)
    return result

def home(request):
    result = render_to_response('cityquest/login.html', context_instance=RequestContext(request))
    return result

def eventlist(request):
    if request.method == 'GET':
        requestCategory = request.GET.get('category','')
	requestLocation = request.GET.get('location','')
        lat = request.GET.get('lat','')
        lon = request.GET.get('lon','')  
        filteredEvents = Event.objects.all().filter(category = requestCategory, public = True)
        events = {}
        distanceList = []
        for event in filteredEvents:
            distance = event.haversine(lon,lat)
            if distance < 30:
                events[distance] = event
                distanceList.append(distance)
	    distanceList.sort()
        result = render_to_response('cityquest/eventlist.html', {'events':events, 'distances': distanceList}, context_instance = RequestContext(request))
    else:
        events = Event.objects.all().filter(public = True)
    	result = render_to_response('cityquest/eventlist.html', {'events':events}, context_instance = RequestContext(request))
    return result

@login_required()
def myprofile(request):
    events = Event.objects.all()
    myevents = Attendee.objects.filter(username = request.user)
    result = render_to_response('cityquest/myprofile.html', {'events': events, "myevents": myevents}, context_instance=RequestContext(request))
    return result

@login_required()
def createevent(request):
    context = RequestContext(request)
    if request.method == 'POST':
        form = EditEventForm(request.POST)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.owner = request.user
            instance.attendees = 1
            instance.slug = slugify(instance.eventname)
            instance.save()
            attendee = Attendee(username = request.user, eventname = instance)
            attendee.save()
            eventID = str(instance.id)
            linkRedirect = "/cq/cityquest/event/" + eventID + "/" + instance.slug
            return HttpResponseRedirect(linkRedirect)
        else:
            print form.errors
    else:
        form = EditEventForm()
    return render_to_response("cityquest/createEvent.html", {'form': form}, context)

@login_required()
def editevent(request, event_id, slug):
    context = RequestContext(request)
    currentEvent = Event.objects.get(id = event_id)
    if request.method == 'POST':
        form = EditEventForm(request.POST, instance = currentEvent)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.slug = slugify(instance.eventname)
            instance.save()
            return event(request, instance.id, instance.slug)
        else:
            print form.errors
    else:
        form = EditEventForm(instance = currentEvent)
#    cache.delete('event_page' + str(event_id))
    return render_to_response("cityquest/editEvent.html", {'form': form, 'event': currentEvent}, context)

@login_required()
def editprofile(request):
    context = RequestContext(request)
    me = get_user_model().objects.get(username = request.user.username)
    if request.method == 'POST':
        form = UserForm(request.POST, instance = me)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/cq/cityquest/myprofile/')
        else:
            print form.errors
    else:
         form = UserForm(instance = me)
    return render_to_response("cityquest/editprofile.html", {'form': form}, context)

@login_required()
def attend(request, event_id):
    currentEvent = get_object_or_404(Event, id = event_id)
    if request.method == 'POST':
        currentEvent.attendees += 1
        currentEvent.save()
        attendee = Attendee(username = request.user, eventname = currentEvent)
        attendee.save()
    eventID = str(event_id)
    linkRedirect = "/cq/cityquest/event/" + eventID + "/" + currentEvent.slug
#    cache.delete('event_page' + str(event_id))
    return HttpResponseRedirect(linkRedirect)

@login_required()
def unattend(request, event_id):
    currentEvent = get_object_or_404(Event, id = event_id)
    if request.method == 'POST':
        currentEvent.attendees -= 1
        currentEvent.save()
        attendee = Attendee.objects.filter(username = request.user).filter(eventname = currentEvent)
        attendee.delete()
    eventID = str(event_id)
    linkRedirect = "/cq/cityquest/event/" + eventID + "/" + currentEvent.slug
#    cache.delete('event_page' + str(event_id))
    return HttpResponseRedirect(linkRedirect)


@login_required()
def commentevent(request, event_id):
    context = RequestContext(request)
    currentEvent = Event.objects.get(id = event_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.username = request.user
            instance.eventname = currentEvent
            instance.save()
            eventID = str(currentEvent.id)
            linkRedirect = "/cq/cityquest/event/" + eventID + "/" + currentEvent.slug
            return HttpResponseRedirect(linkRedirect)
        else:
            print form.errors
    else:
        form = CommentForm()
#    cache.delete('event_page' + str(event_id))
    return render_to_response("cityquest/comment.html", {'form': form, 'event': currentEvent}, context)

cq.git/cityquest/templates/cityquest/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    
    <!-- Bootstrap -->
    <link href="{% static 'cityquest/css/bootstrap.min.css' %}"  rel="stylesheet">
    <link href="{% static 'cityquest/css/cityquest.css' %}"  rel="stylesheet">
    {% block cssfiles %}{% endblock %}
	
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]> 
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <title>{% block title %}NO TITLE{% endblock %}</title>
</head>
  
<body onload = "initialize()">
    <nav class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="http://cmpt470.csil.sfu.ca:8007/cq/cityquest/home/">CityQuest</a>
        {% if user.is_active %}
            <a class="btn btn-default navbar-btn navbar-right" href="http://cmpt470.csil.sfu.ca:8007/cq/logout/" role="button">Logout</a>
            <a href="http://cmpt470.csil.sfu.ca:8007/cq/cityquest/myprofile/" class="btn btn-default navbar-btn navbar-right" title="my profile" role="button">
            <span class="glyphicon glyphicon-user" ></span></a>
            <a href="http://cmpt470.csil.sfu.ca:8007/cq/cityquest/create/" class="btn btn-default navbar-btn navbar-right" title="create event">
            <span class="glyphicon glyphicon-plus" role="button"></span></a>
            <!--welcome <a class="btn btn-default navbar-btn" href="../../profile/{{ user.username }}" role="button">{{ user.username }}</a>-->
        {% else %}
	        <a class="btn btn-default navbar-btn navbar-right" href="http://cmpt470.csil.sfu.ca:8007/cq/register/" role="button">Sign Up</a>
            <a class="btn btn-default navbar-btn navbar-right" href="http://cmpt470.csil.sfu.ca:8007/cq/login/" role="button">Login</a>
        {% endif %}
    </nav>
    <div>
        {% block content %}{% endblock %}
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">#cooltransitions</h4>
                </div>
               
                <div class="modal-body">
                    put text and stuff in here
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" id="generate" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</body>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'cityquest/js/jquery-2.1.1.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'cityquest/js/bootstrap.min.js' %} "></script>


{% block javascript %}{% endblock %}
</html>

cq.git/cityquest/templates/cityquest/comment.html
{% extends 'cityquest/base.html' %}

{% block title %}Make a Comment{% endblock %}

{% block content %}
    <article class="well well-sm">
    <form action = "/cq/cityquest/comment/{{ event.id }}/" method = "POST">{% csrf_token %}

            {% for entry in form %}
                <h4>Leave A Comment</h4> 
		<div>
		{{ entry }}
		</div>
            {% endfor %}

        
	<button type="submit" class="btn btn-success btn-lg">Save</button>    <a role="button" href = "/cq/cityquest/home/" class="btn btn-danger btn-lg">Cancel</a>

    </form>
    </artcle>
{% endblock %}

cq.git/cityquest/templates/cityquest/createEvent.html
{% extends 'cityquest/base.html' %}
{% load static %}

{% block title %}Create an Event{% endblock %}

{% block cssfiles %}
    <link href="{% static 'cityquest/css/bootstrap-datetimepicker.min.css' %}"  rel="stylesheet">
    <link href="{% static 'cityquest/css/createEvent.css' %}"  rel="stylesheet">
{% endblock %}

{% block content %}
    <article class = "well well-sm">
        <form action = "/cq/cityquest/create/" method = "POST" onSubmit="return validate()">{% csrf_token %}

	    <label for = "eventname">Event Name: </label>
	    <br>
	    {{ form.eventname }}
	    <br>

            <label for = "address">Address: </label>
            <div id="locationField">
            <input id = "address" type = "text" name = "address" onFocus="geolocate()" placeholder="Enter an address"></input>
            </div>

            <label for = "datetime">Date and time: </label>
            <div id="datetimepicker1" class="input-append date">
                <input data-format="yyyy-MM-dd hh:mm:ss" type="text" id = "datetime" name = "datetime" placeholder="Select a date"></input>
                <span class="add-on">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
	    <label for = "category">Category: </label>
	    <br>
	    {{ form.category }}
	    <br>
	    <label for = "price">Price: </label>
	    <br>
	    {{ form.price }}
	    <br>
	    <label for = "description">Description: </label>
	    <br>
	    {{ form.description }}
	    <br>
            {{ form.public.label }}: {{ form.public }}
	    <br>
       
            <input type = "hidden" name="latitude" id="latitude" value="">   
            <input type = "hidden" name="longitude" id="longitude" value=""> 

            <input class="btn btn-success btn-lg" type="submit" value="Create event">
            <a href="/cq/cityquest/home/" class="btn btn-danger btn-lg active" role="button">Cancel</a>
        </form>
    </article>
{% endblock %}

{% block javascript %}
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
    <script type="text/javascript" src="{% static 'cityquest/js/createEvent.js' %}"></script>
    <script type="text/javascript" src="{% static 'cityquest/js/bootstrap-datetimepicker.min.js' %}"></script>
{% endblock %}

cq.git/cityquest/templates/cityquest/editEvent.html
{% extends 'cityquest/base.html' %}
{% load static %}

{% block title %}Edit Event{% endblock %}

{% block cssfiles %}
    <link href="{% static 'cityquest/css/bootstrap-datetimepicker.min.css' %}"  rel="stylesheet">
    <link href="{% static 'cityquest/css/createEvent.css' %}"  rel="stylesheet">
{% endblock %}

{% block content %}
    <article class = "well well-sm">
        <form action = "/cq/cityquest/edit/{{ event.id }}/{{ event.slug }}/" method = "POST" onSubmit="return validate()">{% csrf_token %}
            <label for = "eventname">Event Name: </label>
            <br>
            {{ form.eventname }}
            <br>

            <label for = "address">Address: </label>
            <div id="locationField">
            <input id = "address" type = "text" name = "address" onFocus="geolocate()" value="{{ event.address }}"></input>
            </div>

            <label for = "datetime">Date and time: </label>
            <div id="datetimepicker1" class="input-append date">
                <input data-format="yyyy-MM-dd hh:mm:ss" type="text" id = "datetime" name = "datetime" value = "{{ event.datetime|date:"Y-m-d H:i:s" }}"</input>
                <span class="add-on">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>

            <label for = "category">Category: </label>
            <br>
            {{ form.category }}
            <br>
            <label for = "price">Price: </label>
            <br>
            {{ form.price }}
            <br>
            <label for = "description">Description: </label>
            <br>
            {{ form.description }}
            <br>
            {{ form.public.label }}: {{ form.public }}
            <br>
		    
            <input type="hidden" name="latitude" id="latitude" value="{{ event.latitude  }}">
            <input type="hidden" name="longitude" id="longitude" value="{{ event.longitude }}">    
       
            <input class="btn btn-success btn-lg" type="submit" value="Save">
            <a href="/cq/cityquest/event/{{ event.id }}/{{ event.slug }}/" class="btn btn-danger btn-lg active" role="button">Cancel</a>
        </form>
    </article>
{% endblock %}

{% block javascript %}
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
    <script type="text/javascript" src="{% static 'cityquest/js/editEvent.js' %}"></script>
    <script type="text/javascript" src="{% static 'cityquest/js/bootstrap-datetimepicker.min.js' %}"></script>
{% endblock %}

cq.git/cityquest/templates/cityquest/editprofile.html
{% extends 'cityquest/base.html' %}
{% load static %}

{% block title %}Edit my Profile{% endblock %}

{% block cssfiles %}
    <link href="{% static 'cityquest/css/createEvent.css' %}"  rel="stylesheet">
{% endblock %}

{% block content %}
    <article class = "well well-sm">
        <form action = "/cq/cityquest/editprofile/" method = "POST" enctype="multipart/form-data"> {% csrf_token %}
            <ul>
                {% for entry in form %}
                    <label for = "{{ entry.label }}">{{ entry.label }}: <br>{{ entry }}<br>
                {% endfor %}
		
		{% comment %}
		<label for = "about_me">About Me: <br>{{ form.about_me }}<br><br>
		<label for = "ph_number">Phone Number: <br>{{ form.ph_number }}<br><br>
		<label for = "age">Age: <br>{{ form.age }}<br><br>
		<label for = "sex">Sex: <br>{{ form.sex }}<br><br>
		<label for = "location">Home Address: <br>
                <div id="locationField">
                    <input id = "location" type = "text" name = "address" onFocus="geolocate()" placeholder="Enter an address"></input>
                </div>
		{% endcomment %}
		
            </ul>
            <input class="btn btn-success btn-lg" type="submit" value="Save">
            <a href="/cq/cityquest/myprofile/" class="btn btn-danger btn-lg active" role="button">Cancel</a>
        </form>
    </article>
{% endblock %}

cq.git/cityquest/templates/cityquest/event.html
{% extends 'cityquest/base.html' %}
{% load static %}

{% block cssfiles %}<link href="{% static 'cityquest/css/event.css' %}"  rel="stylesheet">{% endblock %}

{% block title %}{{ event.eventname }}{% endblock %}
 
{% block content %}
    <ul class="nav nav-tabs" role="tablist" id="myTab">
        <li class="active"><a href="#Event_Description" role="tab" data-toggle="tab">Event Description</a></li>
        <li><a href="#Attendees" role="tab" data-toggle="tab">Attendees</a></li>
        <li><a href="#Discussion" role="tab" data-toggle="tab">Discussion</a></li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane active" id="Event_Description">
            <article class="well well-sm">
                <h1>{{ event.eventname }}</h1>
                <div id="detail-container">
                    <ul id="eventlist">
                        {% if event.public %}
                            <li><strong>Event type:</strong> Public</li>
                        {% else %}
                            <li><strong>Event type:</strong> Private</li>
                        {% endif %}
                        <li><strong>Host:</strong> {{ owner.username }}</li>
                        <li><strong>Address:</strong> {{ event.address }}</li>
			<li><strong>When:</strong> {{ event.datetime }}</li>
                        <li><strong>Category:</strong> {{ event.get_category_display }}</li>
                        <li><strong>Price:</strong> ${{ event.price }}</li>
                        <li><strong>Attending:</strong> {{ event.attendees }}</li>
                        <li><strong>Description:</strong> {{ event.description }}</li>
                    </ul>
                </div>

                {% if user.id == owner.id %}
                    <a href="/cq/cityquest/edit/{{ event.id }}/{{ event.slug }}/" class="btn btn-primary btn-lg active" role="button">Edit Event</a>
                {% endif %}
            </article>
        </div>
        
        <div class="tab-pane" id="Attendees">
            <article class="well well-sm">
            <h3>People attending:</h3>
                {% if user.is_active %}
                    <ul id="attendees">
                        {% for attendee in attendees %}
                            <li>{{ attendee.username.username }}</li>
                        {% endfor %}
                    </ul>
                    <br>
                    {% if isAttending %}
                        <form action = "/cq/cityquest/unattend/{{ event.id }}/" method = "POST">{% csrf_token %}
                            <input type = "submit" class="btn btn-warning btn-lg active" value = "Remove RSVP"/>
                        </form>
                    {% else %}
                        <form action = "/cq/cityquest/attend/{{ event.id }}/" method = "POST">{% csrf_token %}
                            <input type = "submit" class="btn btn-info btn-lg active" value = "RSVP"/>
                        </form>
                    {% endif %}

                {% else %}
                    <a href="/cq/login" class="btn btn-primary btn-lg active" role="button">Login</a> or
                    <a href="/cq/register" class="btn btn-primary btn-lg active" role="button">Sign up</a> to see who is attending
                {% endif %}
            </article>    
        </div>
  
        <div class="tab-pane" id="Discussion">
            <article class="well well-sm">
                <h1>Discussion Board</h1>
                <p>
                    <ul>
                        {% for comment in comments %}
                            <li>{{ comment.username.username }}: {{ comment.commentbody }}</li>
                        {% endfor %}
                    </ul>
                </p<

                <p>
                    {% if user.is_active %}
                        <a href="/cq/cityquest/comment/{{ event.id }}/" class="btn btn-primary btn-lg active" role="button">Add a comment</a>
                    {% else %}
                        <a href="/cq/login" class="btn btn-primary btn-lg active" role="button">Login</a> or
                        <a href="/cq/register" class="btn btn-primary btn-lg active" role="button">Sign up</a> to participate in the group discussion
                    {% endif %}
                </p>
            </article>
        </div>
    </div>
{% endblock %}

{% block javascript %}
{#    <script type="text/javascript" src="{% static 'cityquest/js/attend.js' %}"></script>#}
{% endblock %}

cq.git/cityquest/templates/cityquest/index.html
{% load staticfiles %}
<head>
    <title>tickly</title>
    <link rel = "stylesheet" type = "text/css" href = "{% static 'cityquest/css/test.css' %}" />
</head>
<body>
    <p>suck my quest</p>
</body>

cq.git/cityquest/templates/cityquest/myprofile.html
{% extends 'cityquest/base.html' %}
{% load static %}

{% block cssfiles %}
    <link rel="stylesheet" href="{% static 'cityquest/css/jquery.e-calendar.css' %}"/>
    <link rel="stylesheet" href="{% static 'cityquest/css/myprofile.css' %}"/>
{% endblock %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <ul class="nav nav-tabs" role="tablist" id="myTab">
        <li class="active"><a href="#profile" role="tab" data-toggle="tab">Profile</a></li>
        <li><a href="#myevents" role="tab" data-toggle="tab">My Events</a></li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane active" id="profile">
            <article class="well well-sm">
            <h1>Hi, {{ user.username }}!</h1>
                <ul id="aboutprof">
                    <li><strong> About me:</strong> {{ user.about_me }}</li>
                    <li><strong> Phone number:</strong> {{ user.ph_number }}</li>
                    <li><strong> Location:</strong> {{ user.location }} </li>
                    <li><strong> Sex:</strong> {{ user.get_sex_display }} </li>
                </ul>
                <a href="/cq/cityquest/editprofile/" class="btn btn-primary btn-lg active" role="button">Edit my profile</a>
            </article>
        </div>
      
        <div class="tab-pane" id="myevents">
            <br>
            <article class="well well-sm">
		<div id="calendar"></div>
                <h4>My Quests:</h4>
                <ul>
                    {% for event in myevents %}
                        <li><a href = "/cq/cityquest/event/{{ event.eventname.id }}/{{ event.eventname.slug }}/">{{ event.eventname.eventname }}</a></li>
                    {% endfor %}
                </ul>
            </article>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'cityquest/js/jquery-1.11.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'cityquest/js/jquery.e-calendar.js' %}"></script>
    <script type="text/javascript" src="{% static 'cityquest/js/myprofile.js' %}"></script>
    
    <script>
        var eventList = [];
        {% for event in myevents %}
            var eventItem = {title: "{{ event.eventname.eventname }}", description: "", datetime: new Date({{event.eventname.datetime|date:"Y,n,j,H"}})};
            eventList.push(eventItem);
        {% endfor %}

        $('#calendar').eCalendar({
            events: eventList
        });
    </script>
{% endblock %}